### ISSUE TITLE
Telemetry App (Beta) from AppSource - Inventory information about Version and Localization not complete

### ISSUE THREAD

**Issue by curateideas** [microsoft/BCTech#126]
We face an issue in the AppSource Version of the app in comparision to the Version from GitHub. 

In the AppSource Version the information for Version and Localization in the Inventory View is not shown for all environments:

![image](https://user-images.githubusercontent.com/58227881/177529743-e36d96ae-ad55-48b4-95fc-69d218a5a412.png)

We extended the period in which data from ApplicationInsights Resource is collected to 180 Days without any effect.

**Comment by jobulsin** [comment]
Fixed in this PR, should roll out to AppSource soon
https://github.com/microsoft/BCTech/pull/127
