### ISSUE TITLE
Documentation: App Insights related articles

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/BCTech#137]
Hi,

I have created two posts around telemetry on my personal blog and I was wondering if I could create a pull request to add these links to your documentation.
The links are these:

Business Central Telemetry – Giving permissions to external user to access telemetry data
https://ricardomoinhos.com/giving-permissions-to-external-user-to-access-telemetry-data/

Business Central telemetry – Exploring telemetry in Excel and using a template file
https://ricardomoinhos.com/exploring-telemetry-in-excel-and-using-a-template-file/

The first one could be included in the VIDEOS section, in the App Insights folder, although it is not a video. There could be a Other Resources  section in the Videos file. Or a new file called RESOURCES.md could be created, instead.
The second one could be included in the Excel folder. I could name it RESOURCES.md, for example.

Hope to hear from you.

Thanks,
Ricardo

**Comment by KennieNP** [comment]
Thanks for your contribution to the community learning. 

See
https://github.com/microsoft/BCTech/blob/master/samples/AppInsights/FAQ.md#i-want-to-learn-about-telemetry-where-are-the-blogs
