### ISSUE TITLE
GDAP authorization

### ISSUE THREAD

**Issue by JASTFM** [microsoft/BCTech#149]
When auth to a customertenant currently in a GDAP adminrelationship I am getting a message that the app I am using is not authorized. Which role do I need towards the customer to be able to auth against it? Is it possible to solve this using an enterprise app- how would I need to configure this in that case?
EDIT:Which GDAP role is needed for auth?

**Comment by ricardopaiva** [comment]
Same issue here. Any news on which GDAP role is needed for auth?

**Comment by JASTFM** [comment]
I solved it, you need to have your user put to the right security group for the Dynamics group

**Comment by chrishdmicrosoftcom** [comment]
Hi, sorry for the very late response here.

You need to set up a normal GDAP relationship with the customer, as described here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/delegated-admin. This includes specifying a security group, and you as a partner employee must be a member of the security group of course. And you must specify a role for the GDAP relationship - here I would recommend Dynamics 365 Admin.

In terms of Admin Center API, it used to be possible to avoid requiring your AAD app to be consented into the customers' AAD tenants. It doesn't look like this is possible anymore. Let me know if you succeeded in getting this to work. Meanwhile, I have updated the documentation so it says that you need to have an admin grant consent in the customer's AAD tenant.

Hope this answers all your questions, please reactive if there are more issues.
