### ISSUE TITLE
Job Queue errors

### ISSUE THREAD

**Issue by mortenbraemer** [microsoft/BCTech#178]
Power BI Report
Errors - Job Queue errors:

Please add Object Name (right now we only have Object Id and Object Type)
Please add Description from "Job Queue Entry Card" (right now we only have Task Id)

**Comment by KennieNP** [comment]
I have asked the team owning this to add dimension alJobQueueObjectName to the Job Queue partner telemetry events

**Comment by mortenbraemer** [comment]
Looking forward to the release
