### ISSUE TITLE
Translate BC to Arabic Language

### ISSUE THREAD

**Issue by abaninas** [microsoft/BCTech#18]
Hi All,
I'm trying to translate business central on another language that is not supported from Microsoft(Arabic Language).

Is there any tool from Microsoft to be used? and how we can translate all labels in BC?

Best Regards,
Ahmad

**Comment by chrishdmicrosoftcom** [comment]
Søren, do you know?

________________________________
Fra: abaninas <notifications@github.com>
Sendt: Sunday, April 5, 2020 4:05:50 PM
Til: microsoft/BCTech <BCTech@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/BCTech] Translate BC to Arabic Language (#18)


Hi All,
I'm trying to translate business central on another language that is not supported from Microsoft(Arabic Language).

Is there any tool from Microsoft to be used? and how we can translate all labels in BC?

Best Regards,
Ahmad

**Comment by sorenfriisalexandersen** [comment]
Unfortunately we do not support Arabic and other right-to-left languages in the web client. Currently this is on our long term roadmap but with no ETA.

**Comment by abaninas** [comment]
Thanks @sorenfriisalexandersen for your reply.

I hope this will be available very soon.

We are ready to help in translating BC to Arabic as we are a Microsoft partner working in Saudi Arabia

**Comment by M-Arif453-afk** [comment]
Hi 
If you have the translation file and using BC Onprem then i can help you with right-to-left. My contact arifm1187@gmail.com
