### ISSUE TITLE
readme.md API calls

### ISSUE THREAD

**Issue by grantbrimhall** [microsoft/BCTech#186]
>>Measurements have shown that it is not unusual to be able to read 2 MB/sec per API call. This means that it is possible to transfer up to 120 MB/min or 720 MB/hour for pipelines running sequentially.

wouldn't it be 7200 MB/hour?

2MB/sec = 2x60 = 120MB/min = 120x60 = 7200MB/hour?

**Comment by KennieNP** [comment]
You are right, thanks for catching that.
