### ISSUE TITLE
ForceHandleTrackingEvent failed to acquire a lock

### ISSUE THREAD

**Issue by LevtechConsultingServices** [microsoft/BCTech#19]
Hi Team,
Hope you are doing well.
Actually I am getting error while publishing on BC Cloud Sandbox after getting WAVE 1 2020 Update.

It says 
The request for path /v2.0/sandbox/dev/apps?SchemaUpdateMode=synchronize&DependencyPublishingOption=default failed with code UnprocessableEntity. Reason: ForceHandleTrackingEvent failed to acquire a lock

But it is allowing to install Manually from Extension Management .

**Comment by freddydk** [comment]
You should create support tickets for issues with Business Central online tenants, you can do this in the administration portal.

**Comment by LevtechConsultingServices** [comment]
Thanks for your reply. We all are working on BC with the hope of always having Microsoft and their expertise with us.

**Comment by LevtechConsultingServices** [comment]
Thanks for your reply.
It started working fine now... :)
We all are working on BC with the hope of always having Microsoft and their expertise with us.
