### ISSUE TITLE
KQL: failurcustomDimensions  does not exist

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/BCTech#22]
https://github.com/microsoft/BCTech/blob/2df7c1c4647b1f9396cc2bc6cd3c89fbc72b6b48/samples/AppInsights/KQL/Reports.kql#L39

The where clause is causing an issue on **failurcustomDimensions** name which does not exist.

I would like to replace it with **customDimensions.result** but not sure.

**Comment by KennieNP** [comment]
Fixed
