### ISSUE TITLE
KQL: Cannot compare values of types string and long

### ISSUE THREAD

**Issue by momoto** [microsoft/BCTech#24]
## Expected behavior

[Long Running SQL Queries.kql] can be executed and shows a result set.

## Actual behavior

It causes a syntax error which says "*Cannot compare values of types string and long.*" and "*The operator '>' is not defined for the operand types string and long.*"

![Cannot-compare-values-of-types-string-and-long](https://user-images.githubusercontent.com/836856/81901596-bc7e2380-95f9-11ea-8cc9-3499156613c7.png)

## Steps to reproduce the behavior

Do the following steps with your web browser:

1. In the [Azure portal], open your Application Insights resource.
1. In the Monitoring menu, select Logs.
1. On the New Query tab, run [Long Running SQL Queries.kql].

[Azure portal]: https://portal.azure.com/
[Long Running SQL Queries.kql]: https://github.com/microsoft/BCTech/blob/master/samples/AppInsights/KQL/Long%20Running%20SQL%20Queries.kql

**Comment by KennieNP** [comment]
Fixed
