### ISSUE TITLE
CopyProductionEnvironmentToSandboxEnvironmentAsync

### ISSUE THREAD

**Issue by lukelu-ca** [microsoft/BCTech#26]
this function calls wrong api.
it should use this API:
Content-Type: application/json
POST /admin/v2.1/applications/{applicationFamily}/environments/{sourceEnvironmentName}
{
  "environmentName": string, // The name of the new environment.
  "type": string // The type of environment to create. Currently only the value "Sandbox" is supported.  
}

**Comment by chrishdmicrosoftcom** [comment]
Thanks! Fixed!
