### ISSUE TITLE
Orderby cannot be parsed in LockTimeouts.kql

### ISSUE THREAD

**Issue by nicolassaleron** [microsoft/BCTech#27]
Hello,

The query currently does not return results but there is a syntax issue line 73.
```orderby``` should be replaced by ```order by```.

https://github.com/microsoft/BCTech/blob/8462058c5df35ab65a80a5ad84090de1449c3a08/samples/AppInsights/KQL/LockTimeouts.kql#L73

**Comment by KennieNP** [comment]
fixed
