### ISSUE TITLE
PerTenant apps

### ISSUE THREAD

**Issue by NSilvergrund** [microsoft/BCTech#29]
Hi!

When I tested the powershell script for getting my customers apps out to a file in the Admincenter API, i didn't get the perTenant apps in it. I really didn't expect that because I can't see it in website either. But is there any way to get them out in similar way? Can't find any entity list anywhere? Did try to google it, nothing out there either.

**Comment by chrishdmicrosoftcom** [comment]
Hi, you're right, the Admin Center API doesn't cover PTEs. You can use the Automation APIs for that: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/itpro-introduction-to-automation-apis#handling-tenant-extensions
