### ISSUE TITLE
Web Services in Business Central

### ISSUE THREAD

**Issue by developmentleasba** [microsoft/BCTech#30]
Good afternoon,
I would like to connect a web application in .Net Core 3.1 with the Business Central web services in a tenant in Europe.
Microsoft Business Central has 3 types of APIs, so which one should I use and how could I do it if I want to copy clients from a website into Business Central?

Best!

**Comment by chrishdmicrosoftcom** [comment]
Hi! I'm not sure I understand the scenario, so feel free to elaborate? Will you have your own registration portal, and when customers fill in details about themselves, you want to automatically create Business Central environments for them?

I'm thinking the following:
  1. Use the Partner Center API (not a Business Central API btw. so it doesn't count as 1 of the 3 you mention) to create the customer in AAD (if necessary) and to purchase the relevant Business Central subscriptions.
  2. Use the Business Central Admin Center API to create Business Central environments
  3. Use the Business Central product APIs that are exposed through app code to initialize the new environments. Notably you should take a look at the Automation APIs.

You can't do everything using an API today, specifically installing AppSource apps is still a manual procedure. But you can get far with automation at least.
