### ISSUE TITLE
Problem with special characters in converted permission sets

### ISSUE THREAD

**Issue by curateideas** [microsoft/BCTech#61]
Problem:

![image](https://user-images.githubusercontent.com/58227881/117120164-4ab36280-ad93-11eb-8cd7-5a2423993dba.png)

After converting permission sets from german database (de-DE), special characters are not converted correctly inside the code.

File name itself is correct.

![image](https://user-images.githubusercontent.com/58227881/117120411-9534df00-ad93-11eb-9aa2-4064fb19646c.png)

Expected behaviour: special characters are converted correctly inside the code

**Comment by grobyns** [comment]
I'll take a look. If you have a suggested fix, feel free to open a PR ;-)
