### ISSUE TITLE
Error in Convert-PermissionSets - Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by hbaehren** [microsoft/BCTech#63]
When using the Convert-PermissionSets module on a databasewith a big number of permission sets and permission set it results in the error "Array dimensions exceeded supported range."

![image](https://user-images.githubusercontent.com/22095707/118005642-d8baba80-b34a-11eb-8ac0-a2b9214546f7.png)

How to reproduce:
- Create a lot of permission sets and permissions on a BC18 database (we have 800 permission sets and 33000 permissions) 
- Run the Convert-PermissionSets module
- Maybe relevant: database is running in docker container

**Comment by grobyns** [comment]
I'll take a look. If you have a suggested fix, feel free to open a PR ;-)

**Comment by grobyns** [comment]
Hi,
I'm unable the repro the issue. The failure happens while downloading symbols from the database, not when getting the permissions so I don't think the number of permissions is the issue.

Can you provide more info about the database you are running this against? (version, localization, extensions published/installed, etc.). and any other info that would help me to repro the issue?

thanks,
Gert
