### ISSUE TITLE
Push Data to BC using ODataV4 with oData connected services

### ISSUE THREAD

**Issue by MakerX101** [microsoft/BCTech#67]
I had publish Purchase Order web service in BC and added connected services by following the step in docs.microsoft.com/.../authenticate-web-services-using-oauth
 
When i try push data to BC PO module, below error came out.
I notice that when I use postman to push data, it had no issue.
May I know how to solve below error?
 
Error
[DataServiceClientException: {"error":{"code":"Unknown","message":"Property \"Editable\" for Pay-to Name is invalid. Expression: [p50PayToOptions = p50PayToOptions::\"Another Vendor\"]

![image](https://user-images.githubusercontent.com/80315295/121876140-ccf05880-cd3b-11eb-83d1-8224e5566aa6.png)

**Comment by chrishdmicrosoftcom** [comment]
Hi MakerX101,

Is your question related to samples in the BCTech repo?

If not, please use another forum to get help.

Thanks,

Christian
